# Generated by Django 4.2.20 on 2025-04-07 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_farmer_user_vet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
